name : first task
on :
   push:
       branches:
           - main
jobs:
    print:
         runs-on: ubuntu-latest
         steps:
             - name : fist task
               run:   echo "hello satya"
             - run : echo "iam learning github actions"
             - name: git version
               run : git -version
             - name : mvn version
               run : mvn -version
             - run: pwd
