name : first task
on :
   push:
       branches:
           - main
jobs:
    print:
         runs-on: ubuntu-latest
         steps:
             - name : fist task
               run:   echo "hello satya"
